# Generated by Django 4.2 on 2024-04-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='text',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=50, verbose_name='title'),
        ),
    ]
